### ISSUE TITLE
Your .jar file does not work

### ISSUE THREAD

**Issue by nourinjh** [osman245/customizable-Venn-Diagram-EECS2311#2]
**OS used**: MacOS
**Release tested**: Latest Release
**Java Version**: Java 11
**Description**: The .jar does not work when double clicked or when opened through the terminal.

**Steps to reproduce:**
1. Right clicked on .jar file
2. Selected "Open"
3. Clicked "Open" again when a pop up appeared
4. Got an error (shown below)

<img width="418" alt="Screen Shot 2020-03-15 at 1 02 40 PM" src="https://user-images.githubusercontent.com/35464664/76706377-62c2b100-66bd-11ea-8786-32280b51ccb0.png">
<img width="520" alt="Screen Shot 2020-03-15 at 1 03 29 PM" src="https://user-images.githubusercontent.com/35464664/76706379-635b4780-66bd-11ea-8b7b-ec8d4b938ae1.png">

**Error when running it in eclipse**:
<img width="399" alt="Screen Shot 2020-03-15 at 1 10 49 PM" src="https://user-images.githubusercontent.com/35464664/76706528-7d495a00-66be-11ea-8505-e6b9c5625f46.png">

**Actual Results**: An error message popped up
**Expected Results**: The java program to open

**Comment by jada246** [comment]
Can you try to run the .jar file in our releases and tell us if you are successful.
